/**
 * Signal Service
 *
 * Handles creation, retrieval, and linking of signals with full client-side
 * encryption. Signal payloads are AES-256-GCM encrypted before being sent
 * to Rust — the backend only ever stores opaque encrypted blobs.
 *
 * Pattern mirrors journalService.ts.
 */

import { invoke } from '@tauri-apps/api/core';
import { encrypt, decrypt } from './crypto';
import type {
  Signal,
  SignalRow,
  SignalType,
  SignalSource,
  SignalPayload,
  SyncLogRow,
} from '../types/signals';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Decrypt a raw SignalRow from Rust into a typed Signal<T> */
async function decryptRow<T extends SignalPayload>(
  row: SignalRow,
  password: string,
): Promise<Signal<T>> {
  const encryptedPayload = JSON.parse(row.payload);
  const result = await decrypt(encryptedPayload, password);
  if (!result.success || result.data === undefined) {
    throw new Error(result.error ?? 'Signal decryption failed');
  }
  const payload = JSON.parse(result.data) as T;

  return {
    id: row.id,
    timestamp: row.timestamp,
    type: row.signal_type as SignalType,
    source: row.source as SignalSource,
    payload,
    synced: row.synced,
    createdAt: row.created_at,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Create a new signal. The payload is encrypted before being sent to Rust.
 *
 * @param password  The user's current session password (for key derivation)
 * @param id        UUID generated by the caller (or crypto.randomUUID())
 * @param timestamp ISO-8601 local timestamp
 * @param type      Signal type
 * @param source    Origin device / platform
 * @param payload   Plaintext payload (will be JSON-encoded then encrypted)
 */
export async function createSignal<T extends SignalPayload>(
  password: string,
  id: string,
  timestamp: string,
  type: SignalType,
  source: SignalSource,
  payload: T,
): Promise<Signal<T>> {
  const plaintext = JSON.stringify(payload);
  const encResult = await encrypt(plaintext, password);
  if (!encResult.success || !encResult.data) {
    throw new Error(encResult.error ?? 'Signal encryption failed');
  }
  const payloadJson = JSON.stringify(encResult.data);

  const row = await invoke<SignalRow>('create_signal', {
    id,
    timestamp,
    signalType: type,
    source,
    payload: payloadJson,
  });

  return decryptRow<T>(row, password);
}

/**
 * Convenience: create a signal with an auto-generated UUID and current timestamp
 */
export async function captureSignal<T extends SignalPayload>(
  password: string,
  type: SignalType,
  source: SignalSource,
  payload: T,
): Promise<Signal<T>> {
  return createSignal(
    password,
    crypto.randomUUID(),
    new Date().toISOString(),
    type,
    source,
    payload,
  );
}

/**
 * List signals, optionally filtered by type. Payloads are decrypted.
 */
export async function listSignals<T extends SignalPayload>(
  password: string,
  signalType?: SignalType,
  limit?: number,
): Promise<Signal<T>[]> {
  const rows = await invoke<SignalRow[]>('list_signals', {
    signalType: signalType ?? null,
    limit: limit ?? null,
  });

  return Promise.all(rows.map((r) => decryptRow<T>(r, password)));
}

/**
 * Link an existing signal to a journal reflection entry (many-to-many).
 */
export async function linkSignalToEntry(
  reflectionId: string,
  signalId: string,
): Promise<void> {
  await invoke('link_signal_to_entry', { reflectionId, signalId });
}

/**
 * Get all signals attached to a journal entry. Payloads are decrypted.
 */
export async function listEntrySignals<T extends SignalPayload>(
  password: string,
  reflectionId: string,
): Promise<Signal<T>[]> {
  const rows = await invoke<SignalRow[]>('list_entry_signals', { reflectionId });
  return Promise.all(rows.map((r) => decryptRow<T>(r, password)));
}

/**
 * Delete a signal.
 */
export async function deleteSignal(id: string): Promise<void> {
  await invoke('delete_signal', { id });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sync log helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch unsynced entries from the sync_log (for incremental sync engines).
 * Used by the WebDAV sync engine and future watch bridge to detect what changed.
 */
export async function getUnsyncedLog(limit?: number): Promise<SyncLogRow[]> {
  return invoke<SyncLogRow[]>('get_unsynced_log', { limit: limit ?? null });
}

/**
 * Mark sync_log rows as synced up to (and including) the given log id.
 * Call this after successfully uploading changed objects to WebDAV / watch.
 */
export async function markSyncLogSynced(upToId: number): Promise<void> {
  await invoke('mark_sync_log_synced', { upToId });
}
