/**
 * AI-related type definitions for MoodHaven Journal
 *
 * Privacy-first approach: Only metadata is sent to AI APIs,
 * never actual journal content.
 */

import type { MoodLevel } from './journal';

// ============================================
// LOCAL METADATA EXTRACTION (Never leaves device)
// ============================================

/** Sentiment classification done locally */
export type SentimentClass = 'positive' | 'negative' | 'neutral' | 'mixed';

/** Emotional indicators extracted locally from text patterns */
export type EmotionalIndicator =
  | 'anxious'
  | 'stressed'
  | 'hopeful'
  | 'grateful'
  | 'sad'
  | 'happy'
  | 'angry'
  | 'calm'
  | 'overwhelmed'
  | 'motivated'
  | 'lonely'
  | 'loved'
  | 'confused'
  | 'confident';

/** Time of day classification */
export type TimeOfDay = 'morning' | 'afternoon' | 'evening' | 'night';

/** Entry frequency pattern */
export type FrequencyPattern = 'daily' | 'regular' | 'sporadic' | 'rare';

/**
 * Metadata extracted locally from a single entry
 * This is processed on-device before any AI calls
 */
export interface EntryMetadata {
  id: string;
  mood: MoodLevel;
  sentiment: SentimentClass;
  emotionalIndicators: EmotionalIndicator[];
  wordCount: number;
  timeOfDay: TimeOfDay;
  dayOfWeek: number; // 0-6
  date: string; // YYYY-MM-DD
  hasGratitude: boolean;
  hasGoals: boolean;
  hasQuestions: boolean;
}

/**
 * Aggregated metadata for AI context
 * This is what gets sent to the AI API - never raw content
 */
export interface AggregatedMetadata {
  periodDays: number;
  totalEntries: number;

  moodStats: {
    average: number;
    trend: 'improving' | 'stable' | 'declining';
    volatility: 'low' | 'medium' | 'high';
    distribution: Record<MoodLevel, number>;
    recentAverage: number; // Last 7 days
  };

  patterns: {
    bestDayOfWeek: string;
    worstDayOfWeek: string;
    bestTimeOfDay: TimeOfDay;
    frequency: FrequencyPattern;
    currentStreak: number;
    longestStreak: number;
  };

  emotionalProfile: {
    dominantIndicators: EmotionalIndicator[];
    recentIndicators: EmotionalIndicator[];
    gratitudeFrequency: number; // 0-1
    goalsFrequency: number; // 0-1
  };

  sentimentBreakdown: {
    positive: number;
    negative: number;
    neutral: number;
    mixed: number;
  };
}

// ============================================
// AI-GENERATED CONTENT (Responses from AI)
// ============================================

/** Journal prompt generated by AI based on patterns */
export interface AIPrompt {
  id: string;
  text: string;
  category: 'gratitude' | 'reflection' | 'goals' | 'emotions' | 'self-care' | 'exploration';
  reasoning: string; // Why this prompt was suggested (shown to user)
  relevance: number; // 0-1 score
}

/** Wellness insight from AI */
export interface WellnessInsight {
  id: string;
  type: 'observation' | 'suggestion' | 'celebration' | 'pattern';
  title: string;
  message: string;
  basedOn: string; // What data this is based on
  actionable: boolean;
  priority: 'low' | 'medium' | 'high';
}

/** Weekly reflection summary */
export interface WeeklyReflection {
  weekStart: string;
  weekEnd: string;
  summary: {
    moodAverage: number;
    moodTrend: 'up' | 'down' | 'stable';
    entryCount: number;
    dominantEmotions: EmotionalIndicator[];
  };
  highlights: string[];
  reflectionPrompts: string[];
  focusSuggestion: string;
}

/** Recurring pattern detected */
export interface RecurringPattern {
  id: string;
  type: 'mood_cycle' | 'weekly_pattern' | 'trigger' | 'positive_habit';
  description: string;
  confidence: number; // 0-1
  frequency: string; // e.g., "Every Monday", "Weekly"
  suggestion?: string;
}

// ============================================
// AI SERVICE TYPES
// ============================================

/** Request to AI for prompts */
export interface PromptGenerationRequest {
  metadata: AggregatedMetadata;
  count: number;
  categories?: AIPrompt['category'][];
  excludeRecent?: string[]; // IDs of recently shown prompts
}

/** Request to AI for insights */
export interface InsightGenerationRequest {
  metadata: AggregatedMetadata;
  focusAreas?: ('mood' | 'patterns' | 'wellness' | 'habits')[];
}

/** AI service response */
export interface AIResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  tokensUsed?: number;
}

// ============================================
// LOCAL KEYWORD PATTERNS (for sentiment analysis)
// ============================================

/** Keywords for local sentiment/emotion detection */
export const EMOTION_KEYWORDS: Record<EmotionalIndicator, string[]> = {
  anxious: ['anxious', 'worried', 'nervous', 'panic', 'fear', 'dread', 'uneasy'],
  stressed: ['stressed', 'overwhelmed', 'pressure', 'tension', 'burden', 'exhausted'],
  hopeful: ['hopeful', 'optimistic', 'looking forward', 'excited', 'anticipate'],
  grateful: ['grateful', 'thankful', 'blessed', 'appreciate', 'fortunate'],
  sad: ['sad', 'depressed', 'down', 'unhappy', 'miserable', 'crying', 'tears'],
  happy: ['happy', 'joyful', 'elated', 'cheerful', 'delighted', 'content'],
  angry: ['angry', 'frustrated', 'annoyed', 'furious', 'irritated', 'mad'],
  calm: ['calm', 'peaceful', 'relaxed', 'serene', 'tranquil', 'at ease'],
  overwhelmed: ['overwhelmed', 'too much', 'cant cope', 'drowning', 'swamped'],
  motivated: ['motivated', 'inspired', 'driven', 'determined', 'energized'],
  lonely: ['lonely', 'isolated', 'alone', 'disconnected', 'abandoned'],
  loved: ['loved', 'supported', 'cared for', 'connected', 'belonging'],
  confused: ['confused', 'uncertain', 'lost', 'unclear', 'unsure'],
  confident: ['confident', 'capable', 'strong', 'empowered', 'self-assured'],
};

export const GRATITUDE_KEYWORDS = [
  'grateful', 'thankful', 'blessed', 'appreciate', 'fortunate',
  'thank you', 'thanks to', 'glad that', 'happy that',
];

export const GOALS_KEYWORDS = [
  'want to', 'going to', 'plan to', 'will', 'goal', 'aim',
  'hope to', 'intend', 'working on', 'trying to',
];

export const QUESTION_PATTERNS = [
  /why\s+(do|did|am|is|are|was|were)/i,
  /how\s+(do|can|should|will)/i,
  /what\s+(if|should|can|do)/i,
  /\?$/,
];
