#!/usr/bin/env python3
"""Generate the gitignored Tauri Android Gradle files from cargo metadata.

`tauri android build/dev` normally writes two machine-specific (and therefore
gitignored) Gradle files that wire the `:app` subproject to the Tauri/plugin
crates living in the local Cargo registry:

  * src-tauri/gen/android/tauri.settings.gradle    — declares the subprojects
  * src-tauri/gen/android/app/tauri.build.gradle.kts — adds them as deps

On a clean CI checkout both are absent, so `settings.gradle` skips `:app`
entirely and `./gradlew :app:...` fails with "project 'app' not found"; once
`:app` resolves, `app/build.gradle.kts` then fails applying the missing
`tauri.build.gradle.kts`. This script reproduces both from `cargo metadata`
(which only needs the registry populated via `cargo fetch`/`cargo metadata`, not
a full Rust build), so a CI job can compile the Android app's Kotlin without
building the Rust .so libs.

Output matches the Tauri-generated files exactly. tauri.settings.gradle:

    // THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    include ':tauri-android'
    project(':tauri-android').projectDir = new File("<tauri_manifest_dir>/mobile/android")
    include ':tauri-plugin-<name>'
    project(':tauri-plugin-<name>').projectDir = new File("<plugin_manifest_dir>/android")

app/tauri.build.gradle.kts:

    // THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    val implementation by configurations
    dependencies {
      implementation("androidx.lifecycle:lifecycle-process:2.10.0")
      implementation(project(":tauri-android"))
      implementation(project(":tauri-plugin-<name>"))
    }
"""
import json
import os
import subprocess
import sys


def main() -> int:
    manifest = os.path.join("src-tauri", "Cargo.toml")
    if not os.path.exists(manifest):
        print(f"error: {manifest} not found (run from repo root)", file=sys.stderr)
        return 1

    out = subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--manifest-path", manifest],
        text=True,
    )
    meta = json.loads(out)

    lines = ["// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."]

    # Deduplicate by name; sort plugins alphabetically (matches Tauri output).
    tauri_dir = None
    plugins = {}
    for pkg in meta["packages"]:
        name = pkg["name"]
        pkg_dir = os.path.dirname(pkg["manifest_path"])
        if name == "tauri":
            android = os.path.join(pkg_dir, "mobile", "android")
            if os.path.isdir(android):
                tauri_dir = android
        elif name.startswith("tauri-plugin-"):
            android = os.path.join(pkg_dir, "android")
            if os.path.isdir(android):
                plugins[name] = android

    if tauri_dir is None:
        print(
            "error: tauri crate (with mobile/android) not found in metadata; "
            "did `cargo fetch`/`cargo metadata` populate the registry?",
            file=sys.stderr,
        )
        return 1

    ordered = sorted(plugins)

    lines.append("include ':tauri-android'")
    lines.append(
        f"project(':tauri-android').projectDir = new File(\"{tauri_dir}\")"
    )
    for name in ordered:
        lines.append(f"include ':{name}'")
        lines.append(
            f"project(':{name}').projectDir = new File(\"{plugins[name]}\")"
        )

    settings_dest = os.path.join("src-tauri", "gen", "android", "tauri.settings.gradle")
    settings_body = "\n".join(lines) + "\n"
    with open(settings_dest, "w") as fh:
        fh.write(settings_body)

    build_lines = [
        "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
        "val implementation by configurations",
        "dependencies {",
        '  implementation("androidx.lifecycle:lifecycle-process:2.10.0")',
        '  implementation(project(":tauri-android"))',
    ]
    for name in ordered:
        build_lines.append(f'  implementation(project(":{name}"))')
    build_lines.append("}")
    build_dest = os.path.join(
        "src-tauri", "gen", "android", "app", "tauri.build.gradle.kts"
    )
    # Tauri writes this file without a trailing newline; match it exactly.
    build_body = "\n".join(build_lines)
    with open(build_dest, "w") as fh:
        fh.write(build_body)

    print(f"wrote {settings_dest}:")
    print(settings_body, end="")
    print(f"wrote {build_dest}:")
    print(build_body, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
