#!/usr/bin/env bash
# Regenerate src-tauri/gen/android/tauri.settings.gradle from Cargo.lock.
#
# Run this after `cargo update` bumps Tauri plugin versions. Without it,
# Gradle fails with "No matching variant of project :tauri-plugin-*".
#
# tauri.settings.gradle is normally auto-generated by `tauri android dev` /
# `tauri android build`, but those commands require an interactive TTY to
# select a device. This script is the non-interactive equivalent for the
# settings file only — it doesn't build anything.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARGO_LOCK="$REPO_ROOT/src-tauri/Cargo.lock"
SETTINGS_FILE="$REPO_ROOT/src-tauri/gen/android/tauri.settings.gradle"

if [[ ! -f "$CARGO_LOCK" ]]; then
  echo "ERROR: $CARGO_LOCK not found" >&2
  exit 1
fi

# Resolve version for a given package name from Cargo.lock
cargo_version() {
  local pkg="$1"
  # Match the first [[package]] block with name = "pkg"
  awk -v pkg="$pkg" '
    /^\[\[package\]\]/ { in_block=1; found=0 }
    in_block && /^name = "/ {
      if ($0 == "name = \"" pkg "\"") found=1
    }
    in_block && found && /^version = "/ {
      gsub(/^version = "|"$/, "")
      print
      exit
    }
  ' "$CARGO_LOCK"
}

# Find the cargo registry source directory (handles hash changes after cargo update)
REGISTRY_SRC=$(find "$HOME/.cargo/registry/src" -maxdepth 1 -name "index.crates.io-*" -type d 2>/dev/null | head -1)
if [[ -z "$REGISTRY_SRC" ]]; then
  echo "ERROR: ~/.cargo/registry/src/index.crates.io-* not found" >&2
  exit 1
fi

# Resolve versions
TAURI_VER=$(cargo_version "tauri")
DIALOG_VER=$(cargo_version "tauri-plugin-dialog")
FS_VER=$(cargo_version "tauri-plugin-fs")
NOTIF_VER=$(cargo_version "tauri-plugin-notification")
SHELL_VER=$(cargo_version "tauri-plugin-shell")

for pkg_label in \
  "tauri $TAURI_VER mobile/android" \
  "tauri-plugin-dialog $DIALOG_VER android" \
  "tauri-plugin-fs $FS_VER android" \
  "tauri-plugin-notification $NOTIF_VER android" \
  "tauri-plugin-shell $SHELL_VER android"
do
  name="${pkg_label%% *}"
  rest="${pkg_label#* }"
  ver="${rest%% *}"
  subpath="${rest#* }"
  dir="$REGISTRY_SRC/$name-$ver/$subpath"
  if [[ ! -d "$dir" ]]; then
    echo "ERROR: $dir not found — run 'cargo fetch' or 'cargo build' first to populate the registry" >&2
    exit 1
  fi
done

cat > "$SETTINGS_FILE" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Regenerate with: scripts/sync-android-settings.sh
include ':tauri-android'
project(':tauri-android').projectDir = new File("$REGISTRY_SRC/tauri-$TAURI_VER/mobile/android")
include ':tauri-plugin-dialog'
project(':tauri-plugin-dialog').projectDir = new File("$REGISTRY_SRC/tauri-plugin-dialog-$DIALOG_VER/android")
include ':tauri-plugin-fs'
project(':tauri-plugin-fs').projectDir = new File("$REGISTRY_SRC/tauri-plugin-fs-$FS_VER/android")
include ':tauri-plugin-notification'
project(':tauri-plugin-notification').projectDir = new File("$REGISTRY_SRC/tauri-plugin-notification-$NOTIF_VER/android")
include ':tauri-plugin-shell'
project(':tauri-plugin-shell').projectDir = new File("$REGISTRY_SRC/tauri-plugin-shell-$SHELL_VER/android")
EOF

echo "Updated $SETTINGS_FILE"
echo "  tauri              $TAURI_VER"
echo "  tauri-plugin-dialog       $DIALOG_VER"
echo "  tauri-plugin-fs           $FS_VER"
echo "  tauri-plugin-notification $NOTIF_VER"
echo "  tauri-plugin-shell        $SHELL_VER"
